data:
  root: dataset
  sino_glob: "sino/*_sino.npy"
  voxel_glob: "voxel/*_voxel.npy"

model:
  enc1:   { base: 64, depth: 8 }
  enc2:   { base: 64, depth: 8 }
  align:  { out_ch: 96, depth: 8, interp_mode: bilinear }
  cheat2d: { enabled: true, base: 64, depth: 8 }
  fusion: { out_ch: 128 }
  dec:    { mid_ch: 128, depth: 8 }

train:
  seed: 1337
  files_per_group: 100
  epochs_per_group: 1
  epochs: 5
  batch_size: 5
  lr: 5.0e-4
  weight_decay: 1.0e-4
  optimizer: "adamw"
  grad_accum_steps: 1
  amp: true
  amp_dtype: "auto"
  compile: false
  num_workers: 2
  ckpt_dir: "results"
  flush_every: 100
  empty_cache_every: 200
  grad_clip: 1.0
  train_ratio: 0.9

losses:
  weights:
    ssim:   0.40
    psnr:   0.20
    band:   0.10
    energy: 0.10
    ver:    0.10
    ipdr:   0.10
    tv:     0.00
  band_low:  0.0
  band_high: 1.0
  ver_thr:   0.1
