data:
  root: dataset
  sino_glob: "sino/*_sino.npy"
  voxel_glob: "voxel/*_voxel.npy"

model:
  enc1:   { base: 32, depth: 3 }
  enc2:   { base: 32, depth: 3 }
  align:  { out_ch: 64, depth: 2 }
  align:  { out_ch: 64, depth: 2, interp_mode: bilinear }
  cheat2d: { enabled: true, base: 16, depth: 2 }
  fusion: { out_ch: 64 }
  dec:    { mid_ch: 64, depth: 3 }

train:
  seed: 1337
  files_per_group: 10
  epochs_per_group: 1
  epochs: 1
  batch_size: 1
  lr: 1.0e-3
  weight_decay: 1.0e-4
  optimizer: "adamw"
  grad_accum_steps: 1
  amp: true
  amp_dtype: "auto"
  compile: false
  num_workers: 0
  ckpt_dir: "ckpt"
  flush_every: 100
  empty_cache_every: 100
  grad_clip: 1.0
  train_ratio: 0.9

losses:
  weights:
    ssim:   0.40
    psnr:   0.20
    band:   0.10
    energy: 0.10
    ver:    0.10
    ipdr:   0.10
    tv:     0.00
  band_low:  0.0
  band_high: 1.0
  ver_thr:   0.1
