# config.yaml

# -----------------------------
# Data (paths & file patterns)
# -----------------------------
data:
  root: "dataset"                  # dataset root folder
  sino_glob: "sino/*_sino.npy"     # sinograms inside dataset/sino
  voxel_glob: "voxel/*_voxel.npy"  # voxels   inside dataset/voxel

# -----------------------------
# Geometry / projector
# -----------------------------
geom:
  voxel_size_xyz: [1.0, 1.0, 1.0]
  det_spacing_xz: [1.0, 1.0]
  angle_chunk: 16
  n_steps_cap: 256

projector:
  method: "joseph3d"               # physics BP (unfiltered)

# -----------------------------
# Model
# -----------------------------
model:
  # encoders
  enc1: { base: 32, depth: 3 }
  enc2: { base: 32, depth: 3 }

  # XA→XY align
  align: { out_ch: 64, depth: 2, interp_mode: "bilinear" }

  # optional GT-cheat path (train only; ignored at inference)
  cheat2d: { enabled: true, base: 16, depth: 2 }

  # XY fusion
  fusion: { out_ch: 64 }

  # XY→XA sino decoder (stack strictly along A)
  sino_dec:
    mid_ch: 64
    depth: 2
    interp_mode: "bilinear"
    bound: "none"                  # {"none","clamp","sigmoid"}
    prefer_gn: 8
    antialias: null                # null→auto when downsampling

  clamp_recon: true                # clamp final recon to [0,1]
  strict_geometry: false

# -----------------------------
# PSF (disabled — not used in training)
# -----------------------------
psf:
  enabled: false
  angle_variant: false
  sigma_u: 0.7
  sigma_v: 0.7

# -----------------------------
# Training (used by train.py)
# -----------------------------
train:
  seed: 1337
  amp: true
  amp_dtype: "auto"
  optimizer: "adamw"
  lr: 1.0e-4
  weight_decay: 1.0e-3
  batch_size: 8
  num_workers: 4
  grad_clip: 1.0
  grad_accum_steps: 1
  train_ratio: 0.8
  files_per_group: 10
  epochs: 1
  epochs_per_group: 2
  ckpt_dir: "results/ckpt"
  compile: false
  flush_every: 1
  empty_cache_every: 100

# -----------------------------
# Losses (masked MSE config)
# -----------------------------
losses:
  expand_thr: 0.8
  expand_spacing: null
  expand_include_in: true
  expand_in_value: 1.0
  expand_boundary_low: 0.8
  expand_boundary_high: 0.9
  expand_clamp: false

# -----------------------------
# Debug
# -----------------------------
debug:
  az_sanity_check: false
